# Codemagic CI/CD configuration for Ethio Tutor
# Documentation: https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1 # Using M1 for fast Flutter builds
    environment:
      flutter: stable
      groups:
        - ai_secrets # You can create this group in Codemagic UI for ADDIS_AI_API_KEY and BASE_URL
      vars:
        PACKAGE_NAME: "com.example.ethio_tutor"
    scripts:
      - name: Set up .env
        script: |
          echo "ADDIS_AI_API_KEY=$ADDIS_AI_API_KEY" > .env
          echo "BASE_URL=$BASE_URL" >> .env
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-shrink --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Update this to your email
        notify:
          success: true
          failure: true
